language: python

cache:
  directories:
    - "$HOME/miniconda3"

addons:
  apt_packages:
    - pandoc

stages:
  - test
  - name: binder
    if: "(branch = master) AND (NOT (type IN (pull_request)))"

jobs:
  include:
  - name: Test
    stage: test
    before_install:
      - . ./bin/install_miniconda.sh
    install:
      - . ./bin/create_testenv.sh
      - pip install codecov
      - conda list && pip freeze
    script:
      - . ./bin/test.sh
      - coverage run -m unittest discover
    after_success:
      - codecov
  - name: Update Binder
    stage: binder
    before_install: skip
    install: skip
    script:
      - bash binder/trigger_binder.sh https://gke.mybinder.org/build/gh/jdtuck/fdasrsf_python/"${TRAVIS_BRANCH}"
      - bash binder/trigger_binder.sh https://ovh.mybinder.org/build/gh/jdtuck/fdasrsf_python/"${TRAVIS_BRANCH}"
    after_success: skip

deploy:
  provider: pypi
    username: __token__
  password:
    secure: k2BJYlPDGAPspTL2U+BGhFevpxFz78JNJut3tGAJjC6/iQohCGy2hqzSpHn4SDlKDGtPROcj500NHC4b3Mfv5WE8XL1rxHc9ovH/5EQC+nXKaT9SrbNCQsKaNSadKY3PKpHp1jse2CKOEZ7I0zMm79m9s2wONQe4vlHTbxxs70QKOYHjK7dgP0FOqxVpElMWm19QXf6SJVjpUmXuj1N0l6b4c/csa41uWXE2ycAAAxLynlJ5gqpZGPCL6j0Dxin6kcyULHUTqGXE/arhmEd9Jz2O7RCK7qOGHE+SArngnrFNh2UGBzt+KOOoewtuvqu0+7QW0ZuoKjNLO9LfxjXgdt5mRYImlmql+Nso8HQwuMT1opasCd8GJQiFxIUYaiHy7J8ZvvWp6jVHNVg7EEGEgfddMH5qN7eQK6Dxv3F6yAHIjnnaxcPXTfdA7V/VUJbZz4hQ00RHnpRQmUDzxJEp5/9s1K1/z9w8y4V8l9/0kmsZMgBJlutW95va1Owjt6l9HTt21/CSkk12v7+RrgyxW6OMPX4uOr2TfVd3KquDqmwY2zLDUKtnq79FezdFFDLzjZSCYE5XE9Lfcmoz8Mitp0hBW4JKsQpq7ZH+FicM5yRtJc8QHbyeQlA9S/bbsOPHE3Z9qmUC/DydPKWWy98njO1HhAy1C5jXUZfwWTy2A90=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
