language: python

cache:
  directories:
    - $HOME/miniconda3

addons:
  apt_packages:
    - pandoc

before_install:
  - . ./bin/install_miniconda.sh

install:
  - . ./bin/create_testenv.sh
  - pip install codecov
  - conda list && pip freeze

after_success:
  - codecov