# appveyor.yml
---
environment:
  # Appveyor machines come with miniconda already installed.
  CONDA_INSTALL_LOCN: "C:\\Miniconda-x64"

  matrix:
  - CONDA: 37

build_script:
  # Build the compiled extension
  - pip install findblas
  - python setup.py build

test_script:
  - python ./bin/tests.py