# appveyor.yml
---
environment:
  matrix:
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy Cython joblib matplotlib patsy tqdm"
  - activate test-environment
  - pip install findblas

build_script:
  # Build the compiled extension
  - python setup.py build

test_script:
  - python ./bin/tests.py